# Generated by Django 5.2.1 on 2025-05-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_bbimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbimage',
            name='image',
        ),
    ]
