# Generated by Django 5.2.1 on 2025-05-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_remove_bbimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='number',
            field=models.CharField(db_index=True, default='+7 (747) 777-70-70', max_length=20, verbose_name='Номер магазина'),
        ),
    ]
