# Generated by Django 5.2.1 on 2025-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_shop_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='image',
        ),
        migrations.AddField(
            model_name='bbimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films_images/', verbose_name='Фото'),
        ),
    ]
