# Generated by Django 5.2.1 on 2025-05-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_remove_bb_image_bbimage_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'rubric')},
        ),
    ]
