# Generated by Django 5.2.1 on 2025-05-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_alter_bb_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
