# Generated by Django 5.2.1 on 2025-05-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_rubric_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
