# Generated by Django 5.2.1 on 2025-05-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_bb_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена в магазине')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.bb', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Цена товара в магазине',
                'verbose_name_plural': 'Цены товаров в магазинах',
                'unique_together': {('shop', 'bb')},
            },
        ),
    ]
